security:
  oauth2:
     client:
        clientId: acme
        clientSecret: acmesecret
        authorized-grant-types: authorization_code,refresh_token,password
        scope: openid
server:
  use-forward-headers: true
